"""initial

Revision ID: 009d418c6884
Revises:
Create Date: 2025-10-22 15:14:33.465677

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "009d418c6884"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chats_id"), table_name="chats")
    op.drop_index(op.f("ix_chats_ozon_chat_id"), table_name="chats")
    op.drop_index(op.f("ix_chats_user_id"), table_name="chats")
    op.drop_table("chats")
    op.drop_index(op.f("ix_messages_chat_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_promo_codes_id"), table_name="promo_codes")
    op.drop_table("promo_codes")
    op.drop_index(op.f("ix_chat_stats_id"), table_name="chat_stats")
    op.drop_table("chat_stats")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_stats",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("total_chats", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("new_chats", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("in_progress", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("declined", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("done", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("error", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("promo_sent", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chat_stats_pkey")),
    )
    op.create_index(op.f("ix_chat_stats_id"), "chat_stats", ["id"], unique=False)
    op.create_table(
        "promo_codes",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("valid_until", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("promo_codes_pkey")),
    )
    op.create_index(op.f("ix_promo_codes_id"), "promo_codes", ["id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("chat_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "sender",
            postgresql.ENUM("user", "system", "manager", name="senderenum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], name=op.f("messages_chat_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("messages_pkey")),
    )
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    op.create_index(op.f("ix_messages_chat_id"), "messages", ["chat_id"], unique=False)
    op.create_table(
        "chats",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("ozon_chat_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "new", "in_progress", "declined", "done", "error", name="chatstatusenum"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chats_pkey")),
    )
    op.create_index(op.f("ix_chats_user_id"), "chats", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_chats_ozon_chat_id"), "chats", ["ozon_chat_id"], unique=True
    )
    op.create_index(op.f("ix_chats_id"), "chats", ["id"], unique=False)
    # ### end Alembic commands ###
